# Generated by Django 5.0.6 on 2024-06-15 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Types_of_invest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Types_of_invest_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_details', models.TextField()),
                ('minimum_investment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=50)),
                ('returns', models.CharField(max_length=100)),
                ('deliverables', models.DateField()),
                ('agreement', models.FileField(upload_to='agreements/')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appback.types_of_invest')),
            ],
        ),
    ]
