# Generated by Django 5.0.6 on 2024-06-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='types_of_invest_details',
            name='agreement',
        ),
    ]
