# Generated by Django 5.0.6 on 2024-06-15 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appback', '0002_remove_types_of_invest_details_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=200)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='appback.types_of_invest')),
            ],
        ),
    ]
