# Generated by Django 5.0.2 on 2024-07-01 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appback', '0005_investmentterm_remove_company_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='company',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='investment_term',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='investment_term',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='InvestmentTerm',
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
