# Generated by Django 5.0.2 on 2024-07-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appback', '0007_company_investmentterm_investment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
