# Generated by Django 5.0.2 on 2024-07-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appback', '0008_investment_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='investmentterm',
            name='term_type',
        ),
    ]
