# Generated by Django 5.0.2 on 2024-07-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appback', '0009_admin_remove_investmentterm_term_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentterm',
            name='short_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
