# Generated by Django 5.0.2 on 2024-07-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appback', '0010_investmentterm_short_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='e_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='e_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
