# Generated by Django 5.0.2 on 2024-07-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appback', '0011_company_e_amt_company_e_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='e_amt',
        ),
        migrations.RemoveField(
            model_name='company',
            name='e_percentage',
        ),
    ]
