# Generated by Django 5.0.2 on 2024-07-20 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appback', '0012_remove_company_e_amt_remove_company_e_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='eqAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_amt', models.IntegerField()),
                ('e_percentage', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eqAP', to='appback.company')),
                ('investment_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eqAP', to='appback.investmentterm')),
            ],
        ),
    ]
