# Generated by Django 5.0.2 on 2024-07-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appback', '0013_eqap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eqap',
            old_name='e_amt',
            new_name='e_amount',
        ),
    ]
