# Generated by Django 5.0.2 on 2024-08-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appback', '0014_rename_e_amt_eqap_e_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentterm',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video_links/'),
        ),
    ]
