# Generated by Django 5.0.2 on 2024-08-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appback', '0016_alter_investmentterm_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='percentage',
            field=models.CharField(max_length=255),
        ),
    ]
