# Generated by Django 5.0.2 on 2024-10-04 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appback', '0017_alter_company_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('investment_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverable', to='appback.investmentterm')),
            ],
        ),
    ]
