# Generated by Django 5.0.2 on 2024-10-04 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appback', '0018_investmentdeliverable'),
        ('userapp', '0014_remove_user_groups_remove_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user'),
        ),
    ]
