# Generated by Django 5.0.2 on 2024-10-05 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appback', '0023_rename_fileurls_c_fileurls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_benefits',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='appback.company'),
        ),
    ]
