# Generated by Django 5.0.2 on 2024-10-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appback', '0024_alter_c_benefits_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='brochureUrl',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
