# Generated by Django 5.0.2 on 2024-10-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appback', '0025_company_brochureurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slot_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
