# Generated by Django 5.0.2 on 2024-10-07 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appback', '0027_company_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_portfolio',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appback.company'),
        ),
        migrations.AlterField(
            model_name='company_portfolio',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appback.slot'),
        ),
    ]
