# Generated by Django 5.0.2 on 2024-08-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_mobileverification_user_billing_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobileVerification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_created_at',
        ),
    ]
