# Generated by Django 5.0.1 on 2024-06-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SIPCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_investment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment_period_years', models.IntegerField()),
                ('returns_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stepup_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
